package dataBaseController;

import java.sql.SQLException;

public class Main {

    public static void main(String[] args) throws SQLException {

        //        Изначально в базе 3 пользователя:
        //        login1 password1 nick1
        //        login2 password2 nick2
        //        login3 password3 nick3

//        DBConn
//                .getInstance()
//                .connection()
//                .prepareStatement("INSERT INTO `test`.`users` (`LOGIN`, `PASS`, `NICK`) " +
//                        "VALUES ('login1', 'password1', 'nick1'); " +
//                        "INSERT INTO `test`.`users` (`LOGIN`, `PASS`, `NICK`) " +
//                        "VALUES ('login2', 'password2', 'nick2'); " +
//                        "INSERT INTO `test`.`users` (`LOGIN`, `PASS`, `NICK`) " +
//                        "VALUES ('login3', 'password3', 'nick3');")
//                .execute();

    }
}
